routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('asdasd', function(){ return \Hash::make('admin');});
Route::get('/', function () {
    return view('welcome');
})->name('main');

Route::get('mision', function(){
    return view('principales.mision');
})->name('mision');

Route::get('vision', function(){
    return view('principales.vision');
})->name('vision');

Route::get('valores', function(){
    return view('principales.valores');
})->name('valores');

Route::get('historia', function(){
    return view('principales.historia');
})->name('historia');

Route::get('organigrama', function(){
    return view('principales.organigrama');
})->name('organigrama');

Route::get('directorio', function () {
    return view('principales.directorio');
})->name('directorio');

Route::get('prestaciones', function () {
    return view('principales.prestaciones');
})->name('prestaciones');

Route::get('convenios', function () {
    return view('principales.convenios');
})->name('convenios');

//---------


Route::get('requisition', function () {
    return view('plain-requisitions');
})->name('requisiciones');

Route::get('requisition/create', function () {
    return view('plain-requisitions-create');
})->name('crear-requisicion');

Route::get('requisition/autorizar', function () {
    return view('plain-requisitions-autorizar');
})->name('autorizar-requisicion');

Route::get('expediente/ver', function () {
    return view('plain-curriculum');
})->name('expediente');

Route::get('mis-postulaciones', function () {
    return view('plain-mis-postulaciones');
})->name('mis-postulaciones');

Route::get('postulantes-puesto', function () {
    return view('plain-postulantes-puesto');
})->name('postulantes-puesto');

Route::get('postularme-encuesta', function () {
    return view('plain-postularme-encuesta');
})->name('postularme-encuesta');

Route::get('vacancies', function () {
    return view('plain-vacantes');
})->name('vacantes');

Route::get('vacancies/list', function () {
    return view('plain-vacantes-list');
})->name('listado-vacantes');

Route::get('vacancies/create', function () {
    return view('plain-vacante-create');
})->name('crear-vacante');

Route::get('vacancies/consulta', function () {
    return view('plain-vacante-consulta');
})->name('consulta-vacante');

Route::get('vacancies/disponibles', function () {
    return view('plain-vacante-disponible');
})->name('vacante-disponible');

/*
 *	Rutas de Importacion y de Moodle
 */
Route::group(['prefix' => 'cron'], function () {
    Route::get('import', 'CronAutomatico\CronController@mainFunction');
});


/**
 *  ================ Announcement Routes ================ 
 */
Route::resource('announcements', 'Announcement\AnnouncementController');
Route::resource('announcement_types', 'Announcement\AnnouncementTypeController');
Route::resource('announcement_categories','Announcement\AnnouncementCategoryController');
Route::resource('views', 'Announcement\ViewController');
Route::resource('announcement_forms', 'Announcement\AnnouncementFormController');
Route::resource('announcement_types_per_view', 'Announcement\AnnouncementTypePerViewController');

Route::get('example', 'Announcement\AnnouncementController@example');
Route::post('announcements/{announcement}/activate', 'Announcement\AnnouncementController@activate');
/**
 *  =============== /Announcement Routes ================
 */

 /**
 *   ================ Admin de Usuarios ================ 
 */
Route::resource('admin-de-usuarios','UserController');
Route::resource('admin-form','EmployeeFormController');

Route::post('admin-de-usuarios/{id}/activate','UserController@activate')->name('activate-user');

Route::resource('direcciones','DirectionController');
Route::resource('departamentos','DepartmentController');
Route::resource('areas','AreaController');

Route::get('trashedDepartments/{id}','DepartmentController@getTrashed')->name('trashed-departments');
Route::get('trashedAreas/{id}','AreaController@trashedAreas')->name('trashed-areas');

Route::get('departments/{id}','PuestoController@departments')->name('departments');
Route::get('area/{id}','PuestoController@areas')->name('area');
Route::get('trashedJobs/{id}','PuestoController@trashedJobs')->name('trashed-jobs');
Route::get('jobpositions/{id}','PuestoController@jobpositions')->name('jobpositions');
Route::get('jobboss','PuestoController@jobboss')->name('jobboss');
Route::get('levels','PuestoController@levels')->name('levels');

// Route::get('organigrama', 'HomeController@organigrama');
Route::get('organigrama-puestos', 'HomeController@organigramaPuestos');
 /**
 *   =============== /Admin de Usuarios ================ 
 */

Route::get('filosofia', 'HomeController@filosofia');
 
//*********************************************************************************
//rutas para la requisición de personal
//inicio
Route::get('requisitions/{id}/autorizar', 'Requisitions\RequisitionController@autorizar');
Route::post('rechazarRequi', 'Requisitions\RequisitionController@rechazar');

Route::resource('requisitions', 'Requisitions\RequisitionController');

//fin
//*********************************************************************************

//*********************************************************************************
//rutas para vacntes de personal y todos los elemetos necesarios
//vacantes - reclutadores
//inicio
Route::get('vacantes_que_es', function () {
    return view ('vacantes.que-es');
});
Route::get('vacantes/showExt/{id}', 'Vacantes\VacantesController@showExt');
Route::get('vacantes/administrar', 'Vacantes\VacantesController@administrar');
Route::get('vacantes/recruiter/{id}', 'Vacantes\VacantesController@recruiter');
Route::post('vacantes/addRecruiter', 'Vacantes\VacantesController@addRecruiter');

Route::get('postulante/{id}/crear', 'Vacantes\PostulanteController@crear');

Route::resources([
  'vacantes' => 'Vacantes\VacantesController',
  'reclutador' => 'Vacantes\ReclutadorController',
  'postulante' => 'Vacantes\PostulanteController'
]);

//fin
//*********************************************************************************

//*********************************************************************************
//rutas para el perfil de personal
//inicio
Route::get('profile/{u}/{p}/{v}/consulta', 'Profile\ProfileController@consulta');
Route::get('profile/{p}/{v}/generar', 'Profile\ProfileController@generar');
Route::post('createBasica', 'Profile\ProfileController@createBasica');
Route::post('createComplementaria', 'Profile\ProfileController@createComplementaria');
Route::post('createRegistro', 'Profile\ProfileController@createRegistro');
Route::put('updateRegistro', 'Profile\ProfileController@updateRegistro');
Route::post('createSalud', 'Profile\ProfileController@createSalud');
Route::put('updateSalud', 'Profile\ProfileController@updateSalud');
Route::post('createBeneficiarios', 'Profile\ProfileController@createBeneficiarios');
Route::put('updateBeneficiarios', 'Profile\ProfileController@updateBeneficiarios');

Route::get('curriculum', 'Profile\ProfileController@curriculum');

Route::resource('profile', 'Profile\ProfileController');
//fin
//*********************************************************************************

/********************************************************************************** */
//rutas para el listado dependiente de estados y municipios
//inicio ***************
Route::get('listStates/{id}', 'Entidades\EntidadesController@listadoMunicipios');
 
//fin
//*************************************************************************

Route::auth();
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Announcement/AnnouncementAttribute.php
<?php

namespace App\Models\Announcement;

use Illuminate\Database\Eloquent\Model;

class AnnouncementAttribute extends Model
{
    /**
     * Fields that can be mass assigned.
     *
     * @var array
     */
    protected $fillable = ['name', 'form_type', 'display_type', 'view_order'];

    /**
     * AnnouncementAttribute has many .
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function forms()
    {
    	// hasMany(RelatedModel, foreignKeyOnRelatedModel = announcementAttribute_id, localKey = id)
    	return $this->hasMany(AnnouncementForm::class);
    }


}

app/Http/Controllers/Announcement/AnnouncementCategoryController.php
<?php

namespace App\Http\Controllers\Announcement;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Announcement\AnnouncementCategory;

class AnnouncementCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = AnnouncementCategory::all();
        return view('announcement.announcement_categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Announcement/AnnouncementFormController.php
<?php

namespace App\Http\Controllers\Announcement;

use File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Announcement\AnnouncementForm;
use App\Models\Announcement\AnnouncementType;
use App\Models\Announcement\AnnouncementAttribute;
use App\Models\Announcement\AnnouncementFormData;


class AnnouncementFormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $canCreateForm = empty(AnnouncementForm::missingForms())?false:true;
        $formShapes = AnnouncementForm::orderBy('announcement_type_id','ASC')
        ->orderBy('view_order','ASC')
        ->get();
        $forms = [];
        foreach ($formShapes as $key => $formShape) {            
            $forms[$formShape->announcementType->name][$formShape->announcementAttribute->name] = $formShape;
        }

        return view('announcement.announcement_forms.index', compact('forms', 'canCreateForm'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = AnnouncementForm::missingForms()->pluck('name','id')->toArray();
        $attributes = AnnouncementAttribute::all();
        return view('announcement.announcement_forms.create', compact('types','attributes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attr_list = isset($request->attr_list)?$request->attr_list:[];
        $attr_list_req = isset($request->attr_list_req)?$request->attr_list_req:[];
        foreach ($attr_list as $key => $attr) {
            $required = (in_array($attr, $attr_list_req))?1:0;
            $form = [
                'announcement_type_id' => $request->type,
                'announcement_attribute_id' => $attr,
                'required' => $required];
                AnnouncementForm::create($form);
        }
        //dd($form);
        
        return redirect()->route('announcement_forms.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $form = AnnouncementForm::where('announcement_type_id',$id)->orderBy('view_order','ASC')->get();

        return view('announcement.announcement_forms.show', compact('form'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $announcement_type = AnnouncementType::find($id);
        $form = AnnouncementForm::where('announcement_type_id',$announcement_type->id)->get();
        $attributes = AnnouncementAttribute::all();
        //dd($attributes);
        foreach ($attributes as $key => $attribute) {
            $attribute->active = false;
            $attribute->required = false;
            foreach ($form as $key2 => $formAttr) {
                if($attribute->id == $formAttr->announcement_attribute_id){
                    $attribute->active = true;
                    $attribute->required = ($formAttr->required)?true:false; 
                }
            }
        }        
        return view('announcement.announcement_forms.edit', compact('attributes','announcement_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request);
        // dd($request->attr_list, $request->attr_list_req, $id);

        if($request->has('attr_list')) {
            $attr_list = $request->attr_list;
            $attr_list_req = ($request->has('attr_list_req')?$request->attr_list_req:null);
            $type = AnnouncementType::with('attributes')->where('id', $id)->first();

            $array_to_update = array();
            $array_to_delete = array();
            foreach($type->attributes as $key => $attribute) {
                if(in_array($attribute->id, $attr_list)) {
                    // array_push($array_to_update, $attribute->id);
                    // Los que se actualizarán
                    if($attr_list_req != null)
                        $attribute->pivot->required = (in_array($attribute->id, $request->attr_list_req)?1:0);
                    else
                        $attribute->pivot->required = 0;
                    $attribute->pivot->save();
                } else {
                    // array_push($array_to_delete, $attribute->id);
                    // Los que se eliminarán
                    if($attribute->attr_view == 'file' || $attribute->attr_view == 'multi-file') {
                        $file_datas = AnnouncementFormData::where('announcement_form_id', $attribute->pivot->id)->get();
                        $destinationPath = 'img/announcements/';
                        foreach($file_datas as $key => $data) {
                            if($attribute->attr_view == 'file') {
                                File::delete($destinationPath.$data->value);
                            } elseif($attribute->attr_view == 'multi-file') {
                                $file_array = json_decode($data->value);
                                foreach($file_array as $file) {
                                    File::delete($destinationPath.$file);
                                }
                            }
                        }
                    }
                    AnnouncementFormData::where('announcement_form_id', $attribute->pivot->id)->delete();
                    $attribute->pivot->delete();
                }
                $index = array_search($attribute->id, $attr_list);
                unset($attr_list[$index]);
            }
            foreach($attr_list as $key => $attribute) {
                // Los que se agregarán
                if($attr_list_req != null)
                    $required = (in_array($attribute, $request->attr_list_req)?1:0);
                else
                    $required = 0;
                AnnouncementForm::insert(array(
                    'announcement_type_id' => $id,
                    'announcement_attribute_id' => $attribute,
                    'required' => $required,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s')
                ));
            }
            // dd($array_to_update, $array_to_delete, $attr_list);
        }
        
        return redirect()->route('announcement_forms.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $form = AnnouncementForm::where('announcement_type_id', $id)->get()
        ->pluck('id')->toArray();
        foreach ($form as $key => $id) {
            AnnouncementForm::find($id)->delete();
        }
        return redirect()->route('announcement_forms.index');
    }
}

resources/views/announcement/announcement_types/create.blade.php
@extends('announcement.app')

@section('title', 'Crear Tipo de Anuncio')

@section('content')

<h1>Esta vista solo la deberia de ver el desarrollador por el momento</h1>
<h3>Para poder nosotros crear un tipo de anuncio es necesario crear la vista que lo tratara, es decir, hacer el archivo blade.php en el cual nosotros le daremos formato a nuestro anuncio, es por esto que <strong>No se puede</strong> crear tipos de anuncios de la nada</h3>

{{--
<div class="row margin-top-20">
	<div class="col-md-12">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			{!! Form::open(['route' => 'admin.announcement-types.store', 'method' => 'POST'])!!}

				@include('announcement-types.partials.form-fields')

				<div class="form-group">
					{!! Form::submit('Agregar', ['class' => 'btn btn-success'])!!}
				</div>
			{!! Form::close() !!}
		</div>
		<div class="col-md-3"></div>
	</div>
</div>
--}}
@endsection

resources/views/announcement/announcement_types/display_announcement.blade.php
@inject('TPV', 'App\Models\Announcement\AnnouncementTypePerView')
@if($TPV::check($announcements['view'],$announcements['type']->id))
<a href="{{url('announcements?view='.$announcements['view'].'&type='.$announcements['type']->id)}}" class="btn btn-primary">Administrar {{$announcements['type']->show_name}}</a>
@include('announcement.announcement_types.views.'.key($announcements), ['announcements' => $announcements[key($announcements)],"type"=>$announcements['type']->id])
@endif

resources/views/announcement/announcement_types/edit.blade.php
@extends('announcement.app')

@section('title', 'Editar Tipo de Anuncio')

@section('content')
<div class="card card-2">
	<div class="card-header">
		<h1>Editar Tipo de Anuncio: {{$announcement_type->name}}</h1>
	</div>
	<div class="card-body">
			<div class="row">
				<div class="col-md-12">
					<form method="POST" action="{{ route('announcement_types.update',$announcement_type->id) }}">
						{!! method_field('PUT') !!}
						{!! csrf_field() !!}	
						<div class="form-group col-12 col-md-12">
							<label for="name" class="col-form-label font-weight-bold">Nombre del Puesto:</label>
							<input type="text" class="form-control" name="name" id="name" value="{{$announcement_type->name}}" required>
						</div>
						<div class="form-group col-12 col-md-12">
							<label for="show_name" class="col-form-label font-weight-bold">Nombre a mostrar:</label>
							<input type="text" class="form-control" name="show_name" id="show_name" value="{{$announcement_type->show_name}}" required>
						</div>
						<div class="form-group col-12 col-md-12">
							<label for="view_file" class="col-form-label font-weight-bold">Archivo de la vista:</label>
							<input type="text" class="form-control" name="view_file" id="view_file" value="{{$announcement_type->view_file}}" required>
							<small id="passwordHelpBlock" class="form-text text-muted">
								Este Archivo es el blade que se sube manualmente y da formato a la vista del tipo de anuncio.
							</small>
						</div>
						<div class="form-group col-12 col-md-12">
							<label for="max_quantity" class="col-form-label font-weight-bold">Número máximo de anuncios de este tipo a mostrar:</label>
							<input type="number" class="form-control" name="max_quantity_stored" id="max_quantity" value="{{$announcement_type->max_quantity_stored}}" required>
						</div>
						<div class="form-group col-12 col-md-12">
							<button type="submit" class="btn btn-success card-1">Guardar Cambios</button>
						</div>
					</form>
				</div>
			</div>
	</div>
	<div class="card-footer text-muted">
	</div>
</div>

<div class="container">
	<div class="row my-5">
		<div class="col text-center">
			
		</div>
	</div>

</div>
@endsection

resources/views/announcement/announcement_types/index.blade.php
@extends('announcement.app')

@section('title', 'Tipos de Anuncios')

@section('content')
<div class="card">
	<div class="card-header">
		<h1>Tipos de Anuncios</h1>
	</div>
	<div class="card-body">
		<div class="row my-4">
			<div class="col text-center">
				<a href="{{url('announcement_types/create')}}" class="btn btn-primary card-1">Agregar</a>
			</div>
		</div>
			
		<table class="table table-striped table-bordered w-100" id="myTable">
			<thead>
				<tr>
					<th>#</th>
					<th>Nombre</th>
					<th>Nombre a Mostrar</th>
					<th>Máximo de Anuncios</th>
					<th>Acciones</th>
				</tr>
			</thead>
				@if ($types->isEmpty())
					<tr class="text-center">
						<td colspan="5">No hay tipos de anuncio</td>
					</tr>
				@endif
				@foreach ($types as $type)
					<tr>
						<td>{{ $loop->iteration }}</td>
						<td>{{ $type->name }}</td>
						<td>{{ $type->show_name }}</td>
						<td>{{ $type->max_quantity_stored }}</td>
						<td>
							<form class="form" action="{{ route('announcement_types.destroy' , $type->id)}}" method="POST">
								<div class="form-row justify-content-center">
									<a class="btn btn-primary mx-1 card-1" href="{{route('announcement_types.edit',$type->id)}}">Editar</a>
									<input name="_method" type="hidden" value="DELETE">
									{{ csrf_field() }}
									<button data-toggle="tooltip" title="Eliminar" type="submit" class="btn btn-danger mx-1 card-1">Eliminar</button>
								</div>
							</form>
						</td>
					</tr>
				@endforeach
			</table>
	</div>
	<div class="card-footer text-muted">

	</div>
</div>
@endsection
@section('mainScripts')
<script>
	$(document).ready( function () {
    	$('#myTable').DataTable();
	});
</script>
@endsection

resources/views/announcement/announcement_types/types.blade.php
@extends('announcement.app')

@section('content')

<div class="card">
	<div class="card-header">
		<h1 class="an-title">Tipos de anuncios para la vista: {{$view->name}}</h1>
	</div>
	<div class="card-body">
			<table class="table table-striped table-bordered w-100" id="myTable">
				<thead>
					<tr>
						<th>#</th>
						<th>Nombre</th>
						<th class="text-center">Activos</th>
						<th class="text-center">Total</th>
						<th>Ir</th>
					</tr>
				</thead>
				<tbody>
					@if ($announcement_types->isEmpty())
						<tr class="text-center">
							<td colspan="5">No hay anuncios disponibles para esta vista</td>
						</tr>
					@endif
					@foreach($announcement_types as $announcement_type)
						<tr>
							<td style="width: 10%">{{ $loop->iteration }}</td>
							<td style="width: 60%">{{$announcement_type->name}}</td>
							@if($announcement_type->countActiveAnnouncementsInView($view->id) > 0)
								<td style="width: 10%" class="text-center"><span class="active-box notification-box">{{$announcement_type->countActiveAnnouncementsInView($view->id)}}</span></td>
							@else
								<td></td>
							@endif
							@if($announcement_type->countAnnouncementsInView($view->id) > 0)
								<td style="width: 10%" class="text-center"><span class="total-box notification-box">{{$announcement_type->countAnnouncementsInView($view->id)}}</span></td>
							@else
								<td></td>
							@endif
							<td style="width: 10%">
							@if($announcement_type->hasFormCreated())
								<a class="btn btn-primary" href="{{url('announcements?view='.$view->id.'&type='.$announcement_type->id)}}">Ver</a>
							@else
								<a class="btn btn-secondary" href="{{url('announcement_forms/create')}}">Crear Formulario</a>
							@endif
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
	</div>
	<div class="card-footer text-muted">
	</div>
</div>
@endsection
@section('mainScripts')
<script>
	$(document).ready( function () {
    	$('#myTable').DataTable();
	});
</script>
@endsection